version: '3'

services:
  web:
    image: lucasfelix/beer-delivery:0.0.1-SNAPSHOT
    depends_on:
      - database
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - DATABASE_NAME=beer
      - DATABASE_USER=beer_admin
      - DATABASE_PASSWORD=cuscuz
      - DATABASE_HOST=database

  database:
    image: mdillon/postgis
    environment:
    - POSTGRES_PASSWORD=cuscuz
    - POSTGRES_USER=beer_admin
    - POSTGRES_DB=beer