spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:beer}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:}
  flyway:
    baseline-on-migrate: true

---
spring:
  profiles: test
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${TEST_DATABASE_NAME:beer_test}
  jpa:
    hibernate:
      ddl-auto: create-drop