spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: true

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/beer_dev
    username: postgres

---
spring:
  flyway:
    enabled: false
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/beer_test
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update